// SowiMotor hi-fi data — bikes, reviews, services. ES + CA strings.

const BIKES = [
  { id: "z900",  name: "Kawasaki Z900",     brand: "Kawasaki", type: "Naked",   year: 2021, km: 12400, price: 7490,  cc: 948, cv: 125, license: "A2", tag: "Recién entrada", color: "Verde lima", images: ["photos/z900.jpg"] },
  { id: "mt07",  name: "Yamaha MT-07",      brand: "Yamaha",   type: "Naked",   year: 2020, km: 18200, price: 5950,  cc: 689, cv: 73,  license: "A2", tag: null,              color: "Negro mate", images: ["photos/mt07.jpg"] },
  { id: "cb650", name: "Honda CB650R",      brand: "Honda",    type: "Naked",   year: 2022, km: 6800,  price: 8200,  cc: 649, cv: 95,  license: "A",  tag: "Garantía 12m",   color: "Rojo grand prix", images: ["photos/cb650.jpg"] },
  { id: "monst", name: "Ducati Monster",    brand: "Ducati",   type: "Naked",   year: 2019, km: 22500, price: 9150,  cc: 821, cv: 109, license: "A",  tag: null,              color: "Rojo Ducati", images: ["photos/monst.jpg"] },
  { id: "pcx",   name: "Honda PCX 125",     brand: "Honda",    type: "Scooter", year: 2021, km: 9100,  price: 2890,  cc: 125, cv: 12,  license: "A1", tag: "A1",             color: "Plata", images: ["photos/pcx.jpg"] },
  { id: "xsr7",  name: "Yamaha XSR 700",    brand: "Yamaha",   type: "Custom",  year: 2020, km: 14300, price: 6200,  cc: 689, cv: 73,  license: "A2", tag: "Top ventas",     color: "Forest green", images: ["photos/xsr7.jpg"] },
  { id: "gs",    name: "BMW R 1250 GS",     brand: "BMW",      type: "Trail",   year: 2019, km: 28000, price: 14500, cc: 1254,cv: 136, license: "A",  tag: null,              color: "Triple negro", images: ["photos/gs.jpg"] },
  { id: "duke",  name: "KTM Duke 390",      brand: "KTM",      type: "Naked",   year: 2022, km: 4500,  price: 4890,  cc: 373, cv: 44,  license: "A2", tag: "A2",             color: "Naranja KTM", images: ["photos/duke.jpg"] },
  { id: "gsxs",  name: "Suzuki GSX-S 750",  brand: "Suzuki",   type: "Sport",   year: 2018, km: 31000, price: 5490,  cc: 749, cv: 114, license: "A",  tag: null,              color: "Azul", images: ["photos/gsxs.jpg"] },
  { id: "tmax",  name: "Yamaha TMAX 530",   brand: "Yamaha",   type: "Scooter", year: 2019, km: 26000, price: 7290,  cc: 530, cv: 46,  license: "A2", tag: null,              color: "Negro", images: ["photos/tmax.jpg"] },
  { id: "v7",    name: "Moto Guzzi V7",     brand: "Moto Guzzi", type: "Custom",year: 2020, km: 11800, price: 7990,  cc: 744, cv: 65,  license: "A2", tag: "Clásica",        color: "Crema", images: ["photos/v7.jpg"] },
  { id: "ninja", name: "Kawasaki Ninja 650",brand: "Kawasaki", type: "Sport",   year: 2021, km: 9700,  price: 6890,  cc: 649, cv: 68,  license: "A2", tag: null,              color: "Verde lima", images: ["photos/ninja.jpg"] },
];

// Pulled from the Google reviews paste.
const REVIEWS = {
  es: [
    {
      name: "Jordi Rebull", initials: "JR", when: "Hace 2 meses",
      quote: "Llevé mi moto a lavar y me la dejaron impecable, como recién salida del concesionario. Una limpieza buena y minuciosa. Gracias a Wilson, atento, amable y profesional. Volveré seguro. Muy recomendable.",
    },
    {
      name: "Smith Herrera", initials: "SH", when: "Hace 2 meses",
      quote: "Excelente servicio y muy buena selección. Al final me llevé una Kawasaki con muy buenas prestaciones.",
    },
    {
      name: "Juanlu Carvajal", initials: "JC", when: "Hace 2 meses",
      quote: "Excelente experiencia en SowiMotor, y especialmente con Wilson. Muy profesional, amable y lo explicó todo claro, sin prisas. Trato cercano y honesto, mucha confianza. ¡Recomendado!",
    },
  ],
  ca: [
    {
      name: "Jordi Rebull", initials: "JR", when: "Fa 2 mesos",
      quote: "Vaig portar la moto a rentar i me la van deixar impecable, com acabada de sortir del concessionari. Una neteja bona i minuciosa. Gràcies al Wilson, atent, amable i professional. Tornaré segur. Molt recomanable.",
    },
    {
      name: "Smith Herrera", initials: "SH", when: "Fa 2 mesos",
      quote: "Excel·lent servei i molt bona selecció. Al final em vaig endur una Kawasaki amb molt bones prestacions.",
    },
    {
      name: "Juanlu Carvajal", initials: "JC", when: "Fa 2 mesos",
      quote: "Excel·lent experiència a SowiMotor, i especialment amb el Wilson. Molt professional, amable i ho va explicar tot clar, sense pressa. Tracte proper i honest, molta confiança. Recomanat!",
    },
  ],
};

const HF_STR = {
  es: {
    nav: { home: "Inicio", catalog: "Motos en venta", services: "Servicios", about: "Quiénes somos", contact: "Contacto" },
    cta: { stock: "Ver el stock", whatsapp: "WhatsApp directo", call: "Llámanos", visit: "Cómo llegar", finance: "Financia desde 89€/mes" },
    hero: {
      kicker: "SOWIMOTOR · BADALONA · DESDE 2018",
      l1: "Tu pasión",
      l2: "sobre ruedas",
      sub: "Compra, venta, alquiler, lavado y mantenimiento de motos en el corazón de Badalona. Motos revisadas, garantía y trato cercano.",
    },
    stats: [
      ["+120", "Motos vendidas"],
      ["5,0★", "53 reseñas Google"],
      ["48H", "Entrega exprés"],
      ["12M", "Garantía incluida"],
    ],
    home: {
      featuredKick: "El garaje",
      featured: "Motos destacadas",
      featuredSub: "Selección semanal del local de Badalona",
      seeAll: "Ver todo el stock",
      svcKick: "Servicios",
      svcTitle: "Lo que hacemos",
      services: [
        ["01", "Compra & Venta", "Motos de ocasión revisadas, garantía y financiación a tu medida."],
        ["02", "Lavamos tu moto", "Te la dejamos como nueva. Productos de calidad, mimo y precio justo."],
        ["03", "Gestión de venta", "¿Vendes tu moto? La tasamos y nos encargamos de todo por ti."],
        ["04", "Alquiler", "Por días o semanas. Casco incluido, papeles al día."],
      ],
      sellKick: "Vende",
      sellTitle: "¿Vendes tu moto?",
      sellSub: "Te la tasamos en 24h. Sin compromiso, sin papeleos, sin dolores de cabeza.",
      sellCta: "Pedir tasación",
      reviewsKick: "Reseñas",
      reviewsTitle: "Lo dicen nuestros clientes",
      reviewsSub: "5,0 ★ · 53 reseñas verificadas en Google",
      visitKick: "Visita",
      visitTitle: "Pasa por el local",
      visitAddr: "Carrer Baldomer Solà 5A, local 1\nesquina C/ Guixeras 42\n08912 Badalona, Barcelona",
      hours: "Horario",
      h: ["Lun – Vie  ·  9:30 – 20:00", "Sábado  ·  9:30 – 14:00", "Domingo y festivos  ·  cerrado"],
      route: "Cómo llegar",
    },
    cat: {
      title: "Motos de ocasión",
      sub: "Stock actualizado en el local de Badalona",
      filters: "Filtros",
      brand: "Marca", type: "Tipo", license: "Carnet", price: "Precio", year: "Año", km: "Km máx",
      reset: "Limpiar filtros",
      results: (n) => `${n} ${n === 1 ? "moto" : "motos"}`,
      empty: "No hay motos con esos filtros. Prueba a quitar alguno.",
      sort: "Ordenar",
      sortOpts: { recent: "Más recientes", priceAsc: "Precio ↑", priceDesc: "Precio ↓", kmAsc: "Menos km" },
    },
    detail: {
      back: "← Volver al catálogo",
      desc: "Descripción",
      descBody: "Moto revisada por nuestro taller, neumáticos al 80%, cadena y kit de transmisión recientes. Un solo propietario, libro de mantenimiento al día. Posibilidad de financiación a tu medida y entrega en 48h. Pasa por el local de Badalona y pruébala.",
      specs: "Ficha técnica",
      ask: "Preguntar por esta moto",
      reserve: "Reservar visita",
      bullets: [
        "Revisión completa pre-entrega",
        "Garantía 12 meses incluida",
        "Financiación desde 89€/mes",
        "Aceptamos tu moto como pago",
      ],
      related: "Otras motos parecidas",
    },
    svc: {
      kicker: "Servicios / Estrella",
      title: "Lavamos la moto por ti",
      sub: "Queremos ver tu moto como nueva. La cuidamos como si fuese nuestra. Bueno, bonito y barato.",
      bookCta: "Reserva por WhatsApp",
      pricesKick: "Tarifas",
      pricesTitle: "Precios claros",
      prices: [
        ["Lavado básico",     "Exterior + secado",                          "15 €"],
        ["Lavado Premium",    "Detalles, llantas, cadena lubricada",        "29 €"],
        ["Detailing completo","2h · interior carenado, plásticos, cera",    "59 €"],
        ["Pre-venta express", "Listo para fotos del anuncio",               "39 €"],
      ],
      bonusKick: "Oferta del mes",
      bonus: "Bono de regalo de mayo",
      bonusBody: "Pregunta por tu bono al pasar por el local.",
    },
    contact: {
      title: "Visítanos",
      sub: "Pasa por el local a charlar, ver motos o reservar lavado. Estamos en Badalona, a 5 minutos del metro.",
      send: "Enviar mensaje",
      sentTitle: "¡Mensaje recibido!",
      sentBody: "Te respondemos en menos de 24h por email o WhatsApp.",
      name: "Nombre", email: "Email", phone: "Teléfono", interest: "Moto de interés (opcional)", msg: "Mensaje",
      btn: "Enviar mensaje",
    },
    foot: {
      tag: "Concesionario de motos de ocasión en Badalona desde 2018",
      visit: "Visítanos", contact: "Contacto", follow: "Síguenos",
      legal: "© 2026 SowiMotor · Aviso legal · Cookies",
    },
  },
  ca: {
    nav: { home: "Inici", catalog: "Motos en venda", services: "Serveis", about: "Qui som", contact: "Contacte" },
    cta: { stock: "Veure l'estoc", whatsapp: "WhatsApp directe", call: "Truca'ns", visit: "Com arribar", finance: "Finança des de 89€/mes" },
    hero: {
      kicker: "SOWIMOTOR · BADALONA · DES DE 2018",
      l1: "La teva passió",
      l2: "sobre rodes",
      sub: "Compra, venda, lloguer, rentat i manteniment de motos al cor de Badalona. Motos revisades, garantia i tracte proper.",
    },
    stats: [
      ["+120", "Motos venudes"],
      ["5,0★", "53 ressenyes Google"],
      ["48H", "Entrega exprés"],
      ["12M", "Garantia inclosa"],
    ],
    home: {
      featuredKick: "El garatge",
      featured: "Motos destacades",
      featuredSub: "Selecció setmanal del local de Badalona",
      seeAll: "Veure tot l'estoc",
      svcKick: "Serveis",
      svcTitle: "Què fem",
      services: [
        ["01", "Compra & Venda", "Motos d'ocasió revisades, garantia i finançament a mida."],
        ["02", "Et rentem la moto", "Te la deixem com nova. Productes de qualitat, mimo i preu just."],
        ["03", "Gestió de venda", "Vens la teva moto? La taxem i ens n'ocupem de tot per tu."],
        ["04", "Lloguer", "Per dies o setmanes. Casc inclòs, papers al dia."],
      ],
      sellKick: "Ven",
      sellTitle: "Vens la teva moto?",
      sellSub: "Te la taxem en 24h. Sense compromís, sense papers, sense maldecaps.",
      sellCta: "Demanar taxació",
      reviewsKick: "Ressenyes",
      reviewsTitle: "Què diuen els clients",
      reviewsSub: "5,0 ★ · 53 ressenyes verificades a Google",
      visitKick: "Visita",
      visitTitle: "Passa pel local",
      visitAddr: "Carrer Baldomer Solà 5A, local 1\ncantonada C/ Guixeras 42\n08912 Badalona, Barcelona",
      hours: "Horari",
      h: ["Dl – Dv  ·  9:30 – 20:00", "Dissabte  ·  9:30 – 14:00", "Diumenge i festius  ·  tancat"],
      route: "Com arribar",
    },
    cat: {
      title: "Motos d'ocasió",
      sub: "Estoc actualitzat al local de Badalona",
      filters: "Filtres",
      brand: "Marca", type: "Tipus", license: "Carnet", price: "Preu", year: "Any", km: "Km màx",
      reset: "Netejar filtres",
      results: (n) => `${n} ${n === 1 ? "moto" : "motos"}`,
      empty: "No hi ha motos amb aquests filtres. Prova de treure'n algun.",
      sort: "Ordenar",
      sortOpts: { recent: "Més recents", priceAsc: "Preu ↑", priceDesc: "Preu ↓", kmAsc: "Menys km" },
    },
    detail: {
      back: "← Tornar al catàleg",
      desc: "Descripció",
      descBody: "Moto revisada al nostre taller, pneumàtics al 80%, cadena i kit de transmissió recents. Un sol propietari, llibre de manteniment al dia. Possibilitat de finançament a mida i entrega en 48h. Passa pel local de Badalona i prova-la.",
      specs: "Fitxa tècnica",
      ask: "Pregunta per aquesta moto",
      reserve: "Reservar visita",
      bullets: [
        "Revisió completa pre-entrega",
        "Garantia 12 mesos inclosa",
        "Finançament des de 89€/mes",
        "Acceptem la teva moto com a pagament",
      ],
      related: "Altres motos semblants",
    },
    svc: {
      kicker: "Serveis / Estrella",
      title: "Et rentem la moto",
      sub: "Volem veure la teva moto com nova. La cuidem com si fos nostra. Bo, bonic i barat.",
      bookCta: "Reserva per WhatsApp",
      pricesKick: "Tarifes",
      pricesTitle: "Preus clars",
      prices: [
        ["Rentat bàsic",       "Exterior + assecat",                            "15 €"],
        ["Rentat Premium",     "Detalls, llantes, cadena lubricada",            "29 €"],
        ["Detailing complet",  "2h · interior carenat, plàstics, cera",         "59 €"],
        ["Pre-venda exprés",   "Llest per a les fotos de l'anunci",             "39 €"],
      ],
      bonusKick: "Oferta del mes",
      bonus: "Bo de regal de maig",
      bonusBody: "Pregunta pel teu bo en passar pel local.",
    },
    contact: {
      title: "Visita'ns",
      sub: "Passa pel local a xerrar, veure motos o reservar el rentat. Som a Badalona, a 5 minuts del metro.",
      send: "Envia missatge",
      sentTitle: "Missatge rebut!",
      sentBody: "Et responem en menys de 24h per email o WhatsApp.",
      name: "Nom", email: "Email", phone: "Telèfon", interest: "Moto d'interès (opcional)", msg: "Missatge",
      btn: "Envia missatge",
    },
    foot: {
      tag: "Concessionari de motos d'ocasió a Badalona des de 2018",
      visit: "Visita'ns", contact: "Contacte", follow: "Segueix-nos",
      legal: "© 2026 SowiMotor · Avís legal · Cookies",
    },
  },
};

window.BIKES = BIKES;
window.REVIEWS = REVIEWS;
window.HF_STR = HF_STR;
